import React from 'react';
import { Link } from 'react-router-dom';
import { CodeBracketIcon, SparklesIcon, BookOpenIcon, UserGroupIcon } from '@heroicons/react/24/outline';

const About = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Hero Section */}
      <div className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="text-center">
            <h1 className="text-4xl md:text-5xl font-bold mb-6">About LogBlog</h1>
            <p className="text-xl text-indigo-100 max-w-3xl mx-auto">
              Empowering developers to learn, build, and share knowledge through comprehensive tutorials and AI-powered learning experiences.
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        {/* Mission Section */}
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Our Mission</h2>
          <p className="text-lg text-gray-600 max-w-4xl mx-auto">
            LogBlog was created to bridge the gap between learning and doing in web development. 
            We believe that the best way to learn is through hands-on practice with real-world projects, 
            guided by comprehensive tutorials and enhanced by AI-powered personalized learning.
          </p>
        </div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-16">
          <div className="text-center">
            <div className="bg-indigo-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <BookOpenIcon className="h-8 w-8 text-indigo-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Comprehensive Tutorials</h3>
            <p className="text-gray-600">
              Step-by-step guides covering everything from basic concepts to advanced techniques.
            </p>
          </div>

          <div className="text-center">
            <div className="bg-purple-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <SparklesIcon className="h-8 w-8 text-purple-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">AI-Powered Learning</h3>
            <p className="text-gray-600">
              Get personalized tutorials generated by AI based on your specific learning needs and goals.
            </p>
          </div>

          <div className="text-center">
            <div className="bg-green-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <CodeBracketIcon className="h-8 w-8 text-green-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Hands-on Projects</h3>
            <p className="text-gray-600">
              Build real-world applications with practical examples and downloadable source code.
            </p>
          </div>

          <div className="text-center">
            <div className="bg-yellow-100 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
              <UserGroupIcon className="h-8 w-8 text-yellow-600" />
            </div>
            <h3 className="text-lg font-semibold text-gray-900 mb-2">Community Driven</h3>
            <p className="text-gray-600">
              Learn from and contribute to a growing community of developers sharing knowledge.
            </p>
          </div>
        </div>

        {/* What We Offer */}
        <div className="bg-white rounded-lg shadow-lg p-8 mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">What We Offer</h2>
          
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">For Beginners</h3>
              <ul className="space-y-3 text-gray-600">
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Getting started guides for web development fundamentals
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  HTML, CSS, and JavaScript basics with interactive examples
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Introduction to modern frameworks like React and Django
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Best practices and coding standards
                </li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">For Advanced Developers</h3>
              <ul className="space-y-3 text-gray-600">
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Complex project architectures and design patterns
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Performance optimization and scalability techniques
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Advanced deployment and DevOps practices
                </li>
                <li className="flex items-start">
                  <span className="text-indigo-600 mr-2">•</span>
                  Integration with AI and machine learning
                </li>
              </ul>
            </div>
          </div>
        </div>

        {/* Technology Stack */}
        <div className="bg-gray-100 rounded-lg p-8 mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">Built With Modern Technology</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">Frontend</h3>
              <div className="space-y-2">
                <div className="flex items-center">
                  <span className="bg-blue-100 text-blue-800 px-2 py-1 text-sm rounded mr-2">React 19</span>
                  <span className="text-gray-600">Modern UI framework</span>
                </div>
                <div className="flex items-center">
                  <span className="bg-cyan-100 text-cyan-800 px-2 py-1 text-sm rounded mr-2">Tailwind CSS</span>
                  <span className="text-gray-600">Utility-first styling</span>
                </div>
                <div className="flex items-center">
                  <span className="bg-purple-100 text-purple-800 px-2 py-1 text-sm rounded mr-2">Vite</span>
                  <span className="text-gray-600">Fast build tool</span>
                </div>
              </div>
            </div>

            <div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">Backend</h3>
              <div className="space-y-2">
                <div className="flex items-center">
                  <span className="bg-green-100 text-green-800 px-2 py-1 text-sm rounded mr-2">Django</span>
                  <span className="text-gray-600">Robust web framework</span>
                </div>
                <div className="flex items-center">
                  <span className="bg-blue-100 text-blue-800 px-2 py-1 text-sm rounded mr-2">PostgreSQL</span>
                  <span className="text-gray-600">Reliable database</span>
                </div>
                <div className="flex items-center">
                  <span className="bg-purple-100 text-purple-800 px-2 py-1 text-sm rounded mr-2">OpenAI API</span>
                  <span className="text-gray-600">AI-powered features</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Call to Action */}
        <div className="text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Ready to Start Learning?</h2>
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
            Join our community and start building amazing projects today. Whether you're a beginner or an expert, 
            we have something for everyone.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/tutorials"
              className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3 rounded-lg font-semibold transition-colors inline-flex items-center justify-center"
            >
              <BookOpenIcon className="h-5 w-5 mr-2" />
              Browse Tutorials
            </Link>
            <Link
              to="/ai-tutorial"
              className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-3 rounded-lg font-semibold transition-colors inline-flex items-center justify-center"
            >
              <SparklesIcon className="h-5 w-5 mr-2" />
              Try AI Tutorial Generator
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
